repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: debug-statements
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.8
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "2.1.3"
  hooks:
    - id: pyproject-fmt
      exclude: docs/examples/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'
    hooks:
    -   id: mypy
        args: [--strict]
        language_version: "3.10"
        additional_dependencies:
            - types-setuptools
            - tokenize-rt==3.2.0
            - pytest == 7.1
            - importlib_metadata
            - typing-extensions>=4.5
            - rich
